<script type="text/javascript">
    var questionID, question, choiceA, choiceB, choiceC, choiceD, questions, numQuestions, qInfo, userChoice, current = 0,
        score = 0,
        points = [];

    var defaultQuestions = [
        {
            question: "Object-Oriented Programming means ?",
            choiceA: "Being objective about what you develop",
            choiceB: "Designing the application based on the objects discovered when analysing the problem",
            choiceC: "Writing an algorithm before writing your program and having a test plan",
            choiceD: "eyes",
            correct: "Writing a program composed of Java classes"
        },
        {
            question: "In java control statements break, continue, return, try-catch-finally and assert belongs to?",
            choiceA: "Selection statements",
            choiceB: "Loop Statements",
            choiceC: "Transfer statements",
            choiceD: "Hydrogen",
            correct: "C"
        },
        {
            question: "Which provides runtime environment for java byte code to be executed?",
            choiceA: "JDK",
            choiceB: "JVM",
            choiceC: "JRE",
            choiceD: "JAVAC",
            correct: "B"
        },
        {
            question: "What is byte code in Java?",
            choiceA: "Code generated by a Java compiler",
            choiceB: "Code generated by a Java Virtual Machine",
            choiceC: "Block of code written inside a class",
            choiceD: "Name of Java source code file",
            correct: "A"
        },
        {
            question: "Which of the following are not Java keywords ?",
            choiceA: "double",
            choiceB: "switch",
            choiceC: "then",
            choiceD: "instanceof",
            correct: "C"
        }];

    // reference HTML elements
    var elQuizStatus = document.getElementById("quizStatus");

    var elQuestion = document.getElementById("question");
    var elChoiceA = document.getElementById("choiceA");
    var elChoiceB = document.getElementById("choiceB");
    var elChoiceC = document.getElementById("choiceC");
    var elChoiceD = document.getElementById("choiceD");
    var elChoices = document.getElementsByName('choices');

    // start quiz
    populateQuestions();
    renderQuestion();
    document.getElementById("submit").onclick = gradeQuestion;

    function populateQuestions(){
        questions = defaultQuestions;
        // if local storage contains questions, add to question set
        if(localStorage.getItem("questions")){
            var storedQuestions = JSON.parse(localStorage.getItem("questions"));
            for(var i = 0; i < storedQuestions.length; i++){
                questions.push(storedQuestions[i]);
            }
        }
        numQuestions = questions.length;
    }

    function populateQuestionInfo(){
        // populate current question info from question list
        question = questions[current].question;
        qInfo = questions[current];
        choiceA = qInfo.choiceA;
        choiceB = qInfo.choiceB;
        choiceC = qInfo.choiceC;
        choiceD = qInfo.choiceD;
        correct = qInfo.correct;
    }

    function renderQuestion(){
        // display question on webpage
        questionID = current + 1;
        elQuizStatus.innerHTML = "Question " + (questionID) + " of " + (numQuestions);
        populateQuestionInfo();
        elQuestion.innerHTML = question;
        elChoiceA.innerHTML = choiceA;
        elChoiceB.innerHTML = choiceB;
        elChoiceC.innerHTML = choiceC;
        elChoiceD.innerHTML = choiceD;
    }

    function gradeQuestion(){
        if(getUserChoice()){
            if(userChoice == questions[current].correct){
                score++;
                points[current] = 1;
            }
            else{
                points[current] = 0;
            }
            // next question
            current++;
            renderQuestion();
        }
    }

    function getUserChoice() {
        for (var i = 0, length = elChoices.length; i < length; i++) {
            if (elChoices[i].checked) {
                userChoice = elChoices[i].value;

                // clear radio input for next question
                elChoices[i].checked = false;

                return true;
            }
        }
        // user didn't select an answer
        alert("Please select an answer before continuing");
        return false;
    }
</script>
</body>
</html>